using MyTreeSetLib;
MyTreeSet<int> tree = new MyTreeSet<int>();
tree.Put(10);
tree.Put(15);
tree.Put(2);
tree.Put(76);
tree.Put(18);
tree.Put(20);
tree.Put(1);
tree.Put(3);
tree.Put(9);
tree.Put(17);
tree.Put(12);
tree.Put(4);
tree.Put(22);
tree.Put(13);
tree.Remove(2);
Console.WriteLine(tree.Last());
tree.Print();